name: main

on:
  schedule:
    - cron: '*/1 * * * *'  # Schedule to run every minute

jobs:
  run-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'

      - name: Run project
        run: MessageSender.py
          
