name: Python application

on:
  schedule:
  - cron: "* * * * * Contest-Reminder/MessageSender.py >/dev/null 2>&1"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install twilio
